- name: StreamSecurityGcpRestartVm
  description: Restarts the Compute Engine VM instance.
  disabled_reason: Action is not applicable because the virtual machine is in a stopped state.
  display_name: Restart Virtual Machine
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_vm_instance
  runbook_owner: StreamSecurity
  role_name: GCP Stream Restart VM Role
  role_file: gcp_restart_vm_role.json
  Parameters:
  - name: VmId
    type: String
    resource_name: true
- name: StreamSecurityGcpIsolatedVMFromAllNetwork
  description: Isolate VM Instance from all firewalls networks
  disabled_reason: Action is not applicable because the isolated firewalls is already attached to the VM instance
  display_name: Isolated VM instance from all network
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_vm_instance
  runbook_owner: StreamSecurity
  role_name: GCP Stream Isolated VM Instance from firewalls Role
  role_file: gcp_isolated_vm_from_firewall.json
  Parameters:
  - name: VmId
    type: String
    resource_name: true
- name: StreamSecurityGcpRemoveServiceAccountFromVM
  description: Detach service account from VM instance
  disabled_reason: Action is not applicable because the virtual machine is not attached to a service account.
  display_name: Detach service account from VM instance
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_vm_instance
  runbook_owner: StreamSecurity
  role_name: GCP Stream Remove Service Account From VM Instance
  role_file: gcp_remove_service_account_from_vm.json
  Parameters:
  - name: VmId
    type: String
    resource_name: true
- name: StreamSecurityGcpVmMIGDetach
  description: Abandons the VM instance from its Managed Instance Group. This prevents the group from automatically replacing or modifying the instance.
  disabled_reason: Action is not applicable because the VM instance is not part of any Managed Instance Group.
  display_name: Abandon Virtual Machine from Managed Instance Group
  resource_type: gcp_vm_instance
  remediation_type: runbook
  cloud_provider: gcp
  runbook_owner: StreamSecurity
  role_name: GCP Stream VM MIG Detach Role
  role_file: vm_mig_detach_policy.json
  Parameters:
  - name: VmId
    type: String
    resource_name: true
  - name: GcpInstanceGroupId
    type: String
- name: StreamSecurityGcpVmCreateDiskSnapshot
  description: Creates point-in-time snapshots of the OS and every data disk, preserving exact disk state for later forensic analysis without touching the running VM.
  display_name: Create Virtual Machine Disks Snapshots
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_vm_instance
  runbook_owner: StreamSecurity
  role_name: Stream GCP Create Disk Snapshot Role
  role_file: gcp_vm_create_snapshot_role.json
  Parameters:
  - name: VmId
    type: String
    resource_name: true
- name: StreamSecurityGcpStopVm
  description: Stop the Compute Engine VM instance.
  disabled_reason: Action is not applicable because the virtual machine is already in a stopped state.
  display_name: Stop Virtual Machine
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_vm_instance
  runbook_owner: StreamSecurity
  role_name: customStopVmRole
  role_file: gcp_stop_vm_role.json
  Parameters:
  - name: VmId
    type: String
    resource_name: true
- name: StreamSecurityGcpEnableVersioningForStorageBucket
  description: Enable versioning for GCP Storage Bucket
  disabled_reason: Action is not applicable because the storage bucket versioning is already enabled.
  display_name: Enable versioning for Storage Bucket
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_bucket
  runbook_owner: StreamSecurity
  role_name: customEnableVersioningForStorageBucketRole
  role_file: gcp_enable_versioning_for_storage_bucket_role.json
  Parameters:
  - name: BucketName
    type: String
    resource_name: true
- name: StreamSecurityGcpReplaceFunctionServiceAccount
  description: Replace the Cloud Run service’s service account with a service account that has no IAM roles assigned.
  disabled_reason: Action is not applicable because the service is already using the service account without roles.
  display_name: Replace Function Service Account with one that has no roles
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_cloud_function
  runbook_owner: StreamSecurity
  role_name: customReplaceFunctionServiceAccountRole
  role_file: gcp_replace_function_service_account_role.json
  Parameters:
  - name: ServiceId
    type: String
    resource_name: true
- name: StreamSecurityGcpDisablePublicAccessBucket
  description: Removes public access from a Google Cloud Storage bucket by updating its IAM policy and ensuring that the identities `allUsers` and `allAuthenticatedUsers` are removed from the bucket's permissions.
  disabled_reason: Action is not applicable because the bucket is not public.
  display_name: Disable Public Access to GCP Storage Bucket
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_bucket
  runbook_owner: StreamSecurity
  role_name: GCP Stream Disable Public Access in bucket
  role_file: gcp_disable_public_access_bucket.json
  Parameters:
  - name: BucketId
    type: String
    resource_name: true
- name: StreamSecurityGcpRemoveIamBindingsFromInstance
  description: Removes all direct IAM role bindings attached to a specific Compute Engine VM instance.
  disabled_reason: Action is not applicable because the VM has no direct IAM role bindings.
  display_name: Remove IAM Role Bindings from VM Instance
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_vm_instance
  runbook_owner: StreamSecurity
  role_name: GCP Remove Iam Role From Instance
  role_file: gcp_remove_iam_role_from_instance.json
  Parameters:
  - name: VmId
    type: String
    resource_name: true
- name: StreamSecurityGcpRemoveAllTcp
  description: Detect and remediate GCP firewall rules that allow unrestricted inbound access to all TCP ports (1-65535 or 0-65535) or IPProtocol=all from 0.0.0.0/0. The runbook disables the rule if it only allows TCP, or updates the rule to remove the TCP-all entry if other protocols are also allowed.
  disabled_reason: Action is not applicable because the firewall rule does not allow all TCP ports (or IPProtocol=all) from the source 0.0.0.0/0.
  display_name: Remove Network Firewall Rule
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_network_firewall_rule
  runbook_owner: StreamSecurity
  role_name: customRemoveAllTcp
  role_file: gcp_remove_all_tcp.json
  Parameters:
  - name: FirewallId
    type: String
    resource_name: true
- name: StreamSecurityGcpDisablePublicIpForCloudSqlInstance
  description: Disable public access to GCP Cloud SQL instance by removing authorized networks and disabling public IP when possible
  disabled_reason: Action is not applicable because SQL IP addresses are private.
  display_name: Disable Public Access for Cloud SQL
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_sql
  runbook_owner: StreamSecurity
  role_name: customDisablePublicIpForCloudSqlInstanceRole
  role_file: gcp_disable_public_ip_for_cloud_sql_instance_role.json
  Parameters:
  - name: InstanceId
    type: String
    resource_name: true
- name: StreamSecurityGcpRemoveExternalIpVm
  description: Remove external IP from VM instance network interfaces
  disabled_reason: Action is not applicable because the virtual machine does not have an external IP address.
  display_name: Remove external IP from VM instance network interfaces
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_vm_instance
  runbook_owner: StreamSecurity
  role_name: GCP Stream Remove External IP From VM Instance
  role_file: gcp_remove_external_ip_from_vm.json
  Parameters:
  - name: VmId
    type: String
    resource_name: true
- name: StreamSecurityGcpEditFirewallRules
  description: Remove public SSH (TCP port 22) access from GCP firewall rules that expose it to 0.0.0.0/0. The runbook disables or updates the rule to block port 22 while preserving other allowed protocols and ports.
  disabled_reason: Action is not applicable because the firewall rule does not allow TCP port 22 from source 0.0.0.0/0.
  display_name: Remove Network Firewall Rule
  remediation_type: runbook
  cloud_provider: gcp
  resource_type: gcp_network_firewall_rule
  runbook_owner: StreamSecurity
  role_name: customEditFirewallRule
  role_file: gcp_edit_firewall_rules.json
  Parameters:
  - name: FirewallId
    type: String
    resource_name: true
